services:
  web_app:
    build:
      context: app
      dockerfile: Dockerfile.flask
    container_name: web_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: mydatabase
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - app-nw
    
    deploy:
      resources:
        limits:
          cpus: '1'    # Max 50% CPU
          memory: 1024M   # Max 512MB RAM
        reservations:
          cpus: '0.5'   # Guaranteed 25% CPU
          memory: 512M   # Guaranteed 256MB RAM
  

   

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - app-nw
    volumes:
      - db_data:/var/lib/postgresql/data


  alert-service:
    build:
      context: alert
      dockerfile: Dockerfile.alert
    container_name: alert-service
    volumes:
      - ./logs:/var/log:ro  # Read-only access to log files
    environment:
      - CONTAINER_NAME=monitor_service
      - ALERT_LOG=/var/log/container_alerts.log
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECIPIENT_EMAILS=${RECIPIENT_EMAILS}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-30}
      - ALERT_COOLDOWN=${ALERT_COOLDOWN:-300}
      - BUFFER_TIMEOUT=${BUFFER_TIMEOUT:-60}
    depends_on:
      - monitor
    restart: unless-stopped
    networks:
      - app-nw



  load:
    build:
      context: load
      dockerfile: Dockerfile.load
    container_name: load_generator
    depends_on:
      - web_app
    environment:
      TARGET_URL: http://web_app:8000
      STRESS_LEVEL: medium
    networks:
      - app-nw

  monitor:
    build:
      context: monitor
      dockerfile: Dockerfile.monitor      
    container_name: monitor_service
    ports:
      - "8001:8001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/var/log
    environment:
      - CONTAINER_NAME=web_app
      - MONITOR_MODE=live 
      - CPU_THRESHOLD="90"
      - MEMORY_THRESHOLD="80"
      - RESPONSE_TIME_THRESHOLD=1000

    command: ["sh", "-c", "python3 dashboard.py & ./monitor_container.sh live"]
    networks:
      - app-nw

volumes:
  db_data:


networks:
  app-nw: